//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfessDirectSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int EnrollmentID { get; set; }
        public Nullable<decimal> Ranking { get; set; }
        public int IndustryID { get; set; }
        public int ContactID { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Industry Industry { get; set; }
    }
}
