//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfessDirectSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProfessDirectDataEntities : DbContext
    {
        public ProfessDirectDataEntities()
            : base("name=ProfessDirectDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<CorpAssociation> CorpAssociations { get; set; }
        public virtual DbSet<CorpDetail> CorpDetails { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Industry> Industries { get; set; }
        public virtual DbSet<KeyTerm> KeyTerms { get; set; }
        public virtual DbSet<Product> Products { get; set; }
    }
}
